name: Timezones 3/5

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install
      - run: ./scripts/test/tzIANA.sh
        env:
          TZ_LENGTH: 4
          TZ_INDEX: 1
