name: Unit tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - name: Node.js tests
        run: npx vitest run

      - run: npx playwright install chromium
      - name: Browser tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npx vitest run --browser

      - name: TZ tests
        run: ./scripts/test/tz.sh
